In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib as plt

In [52]:
def describe_df(df):
    print(f'DataFrame Shape: {df.shape}')
    df_describe = df.describe()
    print(df_describe)
    print(df.isnull().sum())
    for col in df.drop(list(df_describe.columns), axis=1).columns:
        print(f'{col} has {df[col].unique().size} unique values: {df[col].unique()}')

# Exploring "Train_Demographics.csv"

In [3]:
df_demographics = pd.read_csv('Datasets/Train_Demographics.csv')
df_demographics.head(3)

,CustomerID,InsuredAge,InsuredZipCode,InsuredGender,InsuredEducationLevel,InsuredOccupation,InsuredHobbies,CapitalGains,CapitalLoss,Country
0,Cust10000,35,454776,MALE,JD,armed-forces,movies,56700,-48500,India
1,Cust10001,36,454776,MALE,JD,tech-support,cross-fit,70600,-48500,India
2,Cust10002,33,603260,MALE,JD,armed-forces,polo,66400,-63700,India

In [53]:
describe_df(df_demographics)

DataFrame Shape: (28836, 10)
         InsuredAge  InsuredZipCode   CapitalGains    CapitalLoss
count  28836.000000    28836.000000   28836.000000   28836.000000
mean      38.815370   502436.579068   23066.569566  -24940.612429
std        7.996377    72250.868871   27637.813724   27913.209608
min       19.000000   430104.000000       0.000000 -111100.000000
25%       33.000000   448603.000000       0.000000  -50000.000000
50%       38.000000   466691.000000       0.000000       0.000000
75%       44.000000   603848.000000   49000.000000       0.000000
max       64.000000   620962.000000  100500.000000       0.000000
CustomerID                0
InsuredAge                0
InsuredZipCode            0
InsuredGender            30
InsuredEducationLevel     0
InsuredOccupation         0
InsuredHobbies            0
CapitalGains              0
CapitalLoss               0
Country                   2
dtype: int64
CustomerID has 28836 unique values: ['Cust10000' 'Cust10001' 'Cust10002' ... 'Cust9996' 'Cust9997' 'Cust9999']
InsuredGender has 3 unique values: ['MALE' 'FEMALE' nan]
InsuredEducationLevel has 7 unique values: ['JD' 'High School' 'Masters' 'MD' 'Associate' 'College' 'PhD']
InsuredOccupation has 14 unique values: ['armed-forces' 'tech-support' 'exec-managerial' 'adm-clerical'
 'handlers-cleaners' 'craft-repair' 'prof-specialty' 'other-service'
 'priv-house-serv' 'protective-serv' 'farming-fishing' 'sales'
 'transport-moving' 'machine-op-inspct']
InsuredHobbies has 20 unique values: ['movies' 'cross-fit' 'polo' 'dancing' 'sleeping' 'camping' 'golf'
 'paintball' 'base-jumping' 'yachting' 'basketball' 'hiking'
 'bungie-jumping' 'exercise' 'board-games' 'reading' 'skydiving'
 'video-games' 'kayaking' 'chess']
Country has 2 unique values: ['India' nan]

## Notes:
 - 30 datapoints missing gender - can probably drop these
 - 2 datapoints missing country
     - Can probably ignore this column - all values are the same
 - 'One-Hot Encoding' required for:
     - EducationLevel
     - Occupation
     - Hobbies
 - Binarisation required for: 'Gender'

# Exploring Train_Claim.csv

In [40]:
df_claims = pd.read_csv('Datasets/Train_Claim.csv')
df_claims.head(2)

,CustomerID,DateOfIncident,TypeOfIncident,TypeOfCollission,SeverityOfIncident,AuthoritiesContacted,IncidentState,IncidentCity,IncidentAddress,IncidentTime,NumberOfVehicles,PropertyDamage,BodilyInjuries,Witnesses,PoliceReport,AmountOfTotalClaim,AmountOfInjuryClaim,AmountOfPropertyClaim,AmountOfVehicleDamage
0,Cust10000,2015-02-03,Multi-vehicle Collision,Side Collision,Total Loss,Police,State7,City1,Location 1311,17,3,?,1,0,?,65501,13417,6071,46013
1,Cust10001,2015-02-02,Multi-vehicle Collision,Side Collision,Total Loss,Police,State7,City5,Location 1311,10,3,YES,2,1,YES,61382,15560,5919,39903

In [54]:
describe_df(df_claims)

DataFrame Shape: (28836, 19)
       IncidentTime  NumberOfVehicles  BodilyInjuries  AmountOfInjuryClaim  \
count  28836.000000      28836.000000    28836.000000         28836.000000
mean      11.746047          1.823207        0.985782          7337.118428
std        6.170069          0.980099        0.784764          4427.638593
min       -5.000000          1.000000        0.000000             0.000000
25%        6.000000          1.000000        0.000000          4743.750000
50%       12.000000          1.000000        1.000000          7147.000000
75%       17.000000          3.000000        2.000000         10571.250000
max       23.000000          4.000000        2.000000         21450.000000

       AmountOfPropertyClaim  AmountOfVehicleDamage
count           28836.000000           28836.000000
mean             7283.870197           37687.129387
std              4375.842738           17977.048232
min                 0.000000             109.000000
25%              4862.000000           32193.250000
50%              7051.000000           42457.500000
75%             10327.000000           49535.750000
max             23670.000000           79560.000000
CustomerID               0
DateOfIncident           0
TypeOfIncident           0
TypeOfCollission         0
SeverityOfIncident       0
AuthoritiesContacted     0
IncidentState            0
IncidentCity             0
IncidentAddress          0
IncidentTime             0
NumberOfVehicles         0
PropertyDamage           0
BodilyInjuries           0
Witnesses                0
PoliceReport             0
AmountOfTotalClaim       0
AmountOfInjuryClaim      0
AmountOfPropertyClaim    0
AmountOfVehicleDamage    0
dtype: int64
CustomerID has 28836 unique values: ['Cust10000' 'Cust10001' 'Cust10002' ... 'Cust9996' 'Cust9997' 'Cust9999']
DateOfIncident has 72 unique values: ['2015-02-03' '2015-02-02' '2015-01-15' '2015-01-19' '2015-01-09'
 '2015-02-07' '2015-01-30' '2015-01-12' '2015-02-06' '2015-01-25'
 '2015-02-10' '2015-02-22' '2015-02-25' '2015-01-02' '2015-02-28'
 '2015-01-03' '2015-01-29' '2015-02-23' '2015-01-28' '2015-02-26'
 '2015-01-27' '2015-01-16' '2015-01-17' '2015-02-04' '2015-01-05'
 '2015-01-10' '2015-02-11' '2015-01-13' '2015-01-06' '2015-01-07'
 '2015-02-17' '2015-02-12' '2015-02-13' '2015-01-26' '2015-02-21'
 '2015-02-14' '2015-02-15' '2015-01-20' '2015-01-24' '2015-01-08'
 '2015-01-11' '2015-02-09' '2015-02-27' '2015-02-24' '2015-01-18'
 '2015-02-08' '2015-01-22' '2015-02-19' '2015-02-18' '2015-02-16'
 '2015-01-04' '2015-02-05' '2015-01-01' '2015-01-23' '2015-01-21'
 '2015-01-14' '2015-02-20' '2015-01-31' '2015-03-06' '2015-03-01'
 '2015-03-04' '2015-03-03' '2015-03-02' '2015-02-01' '2015-03-05'
 '2015-03-09' '2015-03-11' '2015-03-07' '2015-03-08' '2015-03-12'
 '2015-03-10' '2015-03-14']
TypeOfIncident has 4 unique values: ['Multi-vehicle Collision' 'Single Vehicle Collision' 'Parked Car'
 'Vehicle Theft']
TypeOfCollission has 4 unique values: ['Side Collision' 'Rear Collision' 'Front Collision' '?']
SeverityOfIncident has 4 unique values: ['Total Loss' 'Minor Damage' 'Major Damage' 'Trivial Damage']
AuthoritiesContacted has 5 unique values: ['Police' 'Other' 'Fire' 'Ambulance' 'None']
IncidentState has 7 unique values: ['State7' 'State8' 'State9' 'State5' 'State6' 'State4' 'State3']
IncidentCity has 7 unique values: ['City1' 'City5' 'City6' 'City4' 'City3' 'City2' 'City7']
IncidentAddress has 1000 unique values: ['Location 1311' 'Location 2081' 'Location 1695' 'Location 1440'
 'Location 1521' 'Location 1596' 'Location 2002' 'Location 1341'
 'Location 1799' 'Location 2030' 'Location 1677' 'Location 1963'
 'Location 1449' 'Location 1580' 'Location 1167' 'Location 1261'
 'Location 1793' 'Location 1112' 'Location 2092' 'Location 1292'
 'Location 1024' 'Location 1426' 'Location 1359' 'Location 1228'
 'Location 1990' 'Location 2054' 'Location 1076' 'Location 1025'
 'Location 1372' 'Location 1629' 'Location 1060' 'Location 1189'
 'Location 1518' 'Location 1302' 'Location 1690' 'Location 1469'
 'Location 1593' 'Location 1231' 'Location 2051' 'Location 1362'
 'Location 1916' 'Location 1179' 'Location 1404' 'Location 1842'
 'Location 1834' 'Location 1986' 'Location 1943' 'Location 1345'
 'Location 1326' 'Location 1090' 'Location 1353' 'Location 1703'
 'Location 1863' 'Location 1517' 'Location 1838' 'Location 1966'
 'Location 1767' 'Location 1482' 'Location 1892' 'Location 2001'
 'Location 1620' 'Location 1320' 'Location 1807' 'Location 1104'
 'Location 1177' 'Location 1574' 'Location 1756' 'Location 1089'
 'Location 1942' 'Location 2078' 'Location 1523' 'Location 1858'
 'Location 1582' 'Location 1441' 'Location 2077' 'Location 1131'
 'Location 1935' 'Location 1460' 'Location 1524' 'Location 1773'
 'Location 1824' 'Location 1597' 'Location 1500' 'Location 2074'
 'Location 1330' 'Location 1286' 'Location 1958' 'Location 1346'
 'Location 1944' 'Location 1361' 'Location 1586' 'Location 2096'
 'Location 1573' 'Location 1655' 'Location 1498' 'Location 1409'
 'Location 1654' 'Location 1439' 'Location 1953' 'Location 1995'
 'Location 1435' 'Location 2060' 'Location 1081' 'Location 1595'
 'Location 1194' 'Location 1200' 'Location 1822' 'Location 1543'
 'Location 1212' 'Location 1012' 'Location 1535' 'Location 1419'
 'Location 1375' 'Location 1619' 'Location 1445' 'Location 1757'
 'Location 1370' 'Location 1249' 'Location 1632' 'Location 1882'
 'Location 1230' 'Location 1055' 'Location 1405' 'Location 1117'
 'Location 1288' 'Location 1931' 'Location 1003' 'Location 1227'
 'Location 1579' 'Location 1778' 'Location 1881' 'Location 1885'
 'Location 1011' 'Location 1700' 'Location 1496' 'Location 1591'
 'Location 1026' 'Location 1430' 'Location 1883' 'Location 1541'
 'Location 1052' 'Location 1987' 'Location 2070' 'Location 1027'
 'Location 1467' 'Location 1127' 'Location 1136' 'Location 1683'
 'Location 1915' 'Location 1968' 'Location 1652' 'Location 1840'
 'Location 2053' 'Location 1053' 'Location 1339' 'Location 1264'
 'Location 1310' 'Location 1659' 'Location 1351' 'Location 2084'
 'Location 1859' 'Location 1970' 'Location 1465' 'Location 1639'
 'Location 1146' 'Location 1489' 'Location 1967' 'Location 1626'
 'Location 1471' 'Location 1168' 'Location 1491' 'Location 2014'
 'Location 1411' 'Location 1329' 'Location 1384' 'Location 1945'
 'Location 1667' 'Location 1436' 'Location 1505' 'Location 1067'
 'Location 1999' 'Location 1747' 'Location 1823' 'Location 2062'
 'Location 1739' 'Location 1407' 'Location 2016' 'Location 1098'
 'Location 1835' 'Location 1548' 'Location 2038' 'Location 1453'
 'Location 2068' 'Location 1242' 'Location 1621' 'Location 1408'
 'Location 2013' 'Location 1206' 'Location 1926' 'Location 1262'
 'Location 1554' 'Location 2087' 'Location 1831' 'Location 1381'
 'Location 1305' 'Location 1855' 'Location 1708' 'Location 1733'
 'Location 1042' 'Location 1609' 'Location 1437' 'Location 2012'
 'Location 1124' 'Location 1741' 'Location 1800' 'Location 1423'
 'Location 1294' 'Location 1810' 'Location 1013' 'Location 1828'
 'Location 1020' 'Location 1668' 'Location 1422' 'Location 2021'
 'Location 1309' 'Location 1327' 'Location 1352' 'Location 1155'
 'Location 1720' 'Location 1056' 'Location 1515' 'Location 1998'
 'Location 1940' 'Location 1037' 'Location 1813' 'Location 1910'
 'Location 1391' 'Location 1468' 'Location 1238' 'Location 2082'
 'Location 2044' 'Location 1786' 'Location 1259' 'Location 1235'
 'Location 1670' 'Location 1223' 'Location 1443' 'Location 1126'
 'Location 1364' 'Location 1504' 'Location 1985' 'Location 1486'
 'Location 1038' 'Location 1663' 'Location 1041' 'Location 1447'
 'Location 1214' 'Location 1884' 'Location 1001' 'Location 1150'
 'Location 1480' 'Location 1234' 'Location 1714' 'Location 1730'
 'Location 1097' 'Location 1044' 'Location 1047' 'Location 2083'
 'Location 1332' 'Location 1928' 'Location 1750' 'Location 1644'
 'Location 2006' 'Location 1559' 'Location 1601' 'Location 1385'
 'Location 1356' 'Location 1991' 'Location 1680' 'Location 1221'
 'Location 1360' 'Location 1474' 'Location 1638' 'Location 1448'
 'Location 1275' 'Location 2091' 'Location 2100' 'Location 1344'
 'Location 1529' 'Location 1774' 'Location 1957' 'Location 1718'
 'Location 1108' 'Location 1516' 'Location 1349' 'Location 1497'
 'Location 1226' 'Location 1425' 'Location 1450' 'Location 2026'
 'Location 1400' 'Location 1289' 'Location 1421' 'Location 1955'
 'Location 1929' 'Location 1843' 'Location 1503' 'Location 1245'
 'Location 1615' 'Location 1438' 'Location 1100' 'Location 1253'
 'Location 2090' 'Location 1583' 'Location 1466' 'Location 1444'
 'Location 1777' 'Location 1755' 'Location 1901' 'Location 1765'
 'Location 1537' 'Location 2027' 'Location 1538' 'Location 1006'
 'Location 1771' 'Location 1045' 'Location 1600' 'Location 1240'
 'Location 1093' 'Location 1542' 'Location 1096' 'Location 1584'
 'Location 1217' 'Location 1002' 'Location 1571' 'Location 1273'
 'Location 1145' 'Location 1196' 'Location 1087' 'Location 1510'
 'Location 1507' 'Location 1520' 'Location 1051' 'Location 1457'
 'Location 1971' 'Location 1284' 'Location 2029' 'Location 1338'
 'Location 1128' 'Location 1594' 'Location 1623' 'Location 1552'
 'Location 1649' 'Location 1137' 'Location 1553' 'Location 1819'
 'Location 1433' 'Location 1374' 'Location 1948' 'Location 1144'
 'Location 1387' 'Location 1307' 'Location 1199' 'Location 1147'
 'Location 1250' 'Location 1715' 'Location 1726' 'Location 1476'
 'Location 1962' 'Location 1735' 'Location 1394' 'Location 1866'
 'Location 1876' 'Location 1004' 'Location 1598' 'Location 1039'
 'Location 1308' 'Location 1645' 'Location 1577' 'Location 1941'
 'Location 1624' 'Location 1290' 'Location 1846' 'Location 1232'
 'Location 1754' 'Location 1007' 'Location 1256' 'Location 1077'
 'Location 1723' 'Location 1949' 'Location 1952' 'Location 1070'
 'Location 1912' 'Location 1401' 'Location 1870' 'Location 1847'
 'Location 1894' 'Location 1148' 'Location 2089' 'Location 1161'
 'Location 1792' 'Location 1058' 'Location 1528' 'Location 1225'
 'Location 1576' 'Location 1064' 'Location 1759' 'Location 1159'
 'Location 1974' 'Location 1511' 'Location 1745' 'Location 1121'
 'Location 1839' 'Location 1917' 'Location 1861' 'Location 1304'
 'Location 1641' 'Location 1158' 'Location 1906' 'Location 1178'
 'Location 1218' 'Location 2097' 'Location 1907' 'Location 1239'
 'Location 1152' 'Location 1788' 'Location 1287' 'Location 1872'
 'Location 1123' 'Location 1140' 'Location 1920' 'Location 1185'
 'Location 1092' 'Location 1712' 'Location 2056' 'Location 1085'
 'Location 1979' 'Location 1947' 'Location 1492' 'Location 1257'
 'Location 1473' 'Location 1015' 'Location 2018' 'Location 1675'
 'Location 1255' 'Location 1017' 'Location 1558' 'Location 1851'
 'Location 1561' 'Location 1187' 'Location 1815' 'Location 1776'
 'Location 1997' 'Location 1821' 'Location 1297' 'Location 1646'
 'Location 1186' 'Location 1530' 'Location 1010' 'Location 1392'
 'Location 1182' 'Location 1176' 'Location 1118' 'Location 1005'
 'Location 1865' 'Location 1869' 'Location 1258' 'Location 1610'
 'Location 1764' 'Location 1827' 'Location 2041' 'Location 1845'
 'Location 1832' 'Location 1368' 'Location 1016' 'Location 1295'
 'Location 1526' 'Location 1630' 'Location 1029' 'Location 1938'
 'Location 2022' 'Location 1818' 'Location 1694' 'Location 1246'
 'Location 1412' 'Location 2098' 'Location 2075' 'Location 2042'
 'Location 1618' 'Location 1904' 'Location 1057' 'Location 1485'
 'Location 1063' 'Location 1276' 'Location 1172' 'Location 1588'
 'Location 2095' 'Location 1366' 'Location 1105' 'Location 1556'
 'Location 1686' 'Location 1210' 'Location 1348' 'Location 1251'
 'Location 1321' 'Location 1671' 'Location 1209' 'Location 2049'
 'Location 2099' 'Location 1648' 'Location 1135' 'Location 1816'
 'Location 1951' 'Location 1877' 'Location 1424' 'Location 1934'
 'Location 1705' 'Location 1282' 'Location 1527' 'Location 1395'
 'Location 1220' 'Location 1354' 'Location 2023' 'Location 1247'
 'Location 1706' 'Location 1080' 'Location 1608' 'Location 2003'
 'Location 1853' 'Location 1642' 'Location 1692' 'Location 1748'
 'Location 1431' 'Location 1195' 'Location 1418' 'Location 1713'
 'Location 1661' 'Location 1544' 'Location 1281' 'Location 1110'
 'Location 1830' 'Location 1737' 'Location 1171' 'Location 1513'
 'Location 1913' 'Location 1569' 'Location 1312' 'Location 1785'
 'Location 1031' 'Location 2007' 'Location 2005' 'Location 1028'
 'Location 1062' 'Location 2071' 'Location 1617' 'Location 1744'
 'Location 1939' 'Location 1796' 'Location 2061' 'Location 1406'
 'Location 1585' 'Location 1678' 'Location 2052' 'Location 2046'
 'Location 1699' 'Location 1021' 'Location 1791' 'Location 1219'
 'Location 1867' 'Location 1685' 'Location 1669' 'Location 1298'
 'Location 2069' 'Location 1481' 'Location 1271' 'Location 1363'
 'Location 1959' 'Location 2032' 'Location 1762' 'Location 1983'
 'Location 1634' 'Location 1046' 'Location 1676' 'Location 1805'
 'Location 2033' 'Location 1633' 'Location 1432' 'Location 1272'
 'Location 1114' 'Location 1738' 'Location 1296' 'Location 1658'
 'Location 1874' 'Location 1972' 'Location 2067' 'Location 2065'
 'Location 1772' 'Location 1048' 'Location 1488' 'Location 1982'
 'Location 1672' 'Location 1502' 'Location 1662' 'Location 1787'
 'Location 1566' 'Location 1900' 'Location 1650' 'Location 1722'
 'Location 1483' 'Location 1086' 'Location 1864' 'Location 1303'
 'Location 1873' 'Location 2037' 'Location 1770' 'Location 1862'
 'Location 1808' 'Location 1969' 'Location 1514' 'Location 1531'
 'Location 1416' 'Location 1040' 'Location 1532' 'Location 1682'
 'Location 1454' 'Location 1752' 'Location 1587' 'Location 1050'
 'Location 1035' 'Location 1285' 'Location 1134' 'Location 1094'
 'Location 1501' 'Location 1494' 'Location 1981' 'Location 1781'
 'Location 1635' 'Location 1666' 'Location 1751' 'Location 1783'
 'Location 1236' 'Location 1082' 'Location 1009' 'Location 1844'
 'Location 1268' 'Location 1809' 'Location 1069' 'Location 1141'
 'Location 1918' 'Location 1184' 'Location 2076' 'Location 1188'
 'Location 1927' 'Location 1506' 'Location 1896' 'Location 1728'
 'Location 1402' 'Location 2010' 'Location 1889' 'Location 1539'
 'Location 1886' 'Location 1109' 'Location 1157' 'Location 1509'
 'Location 1111' 'Location 1673' 'Location 2048' 'Location 1133'
 'Location 1919' 'Location 1534' 'Location 1612' 'Location 1074'
 'Location 1709' 'Location 2024' 'Location 1328' 'Location 2036'
 'Location 1054' 'Location 1241' 'Location 1278' 'Location 1207'
 'Location 1066' 'Location 1018' 'Location 1033' 'Location 1315'
 'Location 1248' 'Location 1378' 'Location 1833' 'Location 2085'
 'Location 1549' 'Location 1812' 'Location 1174' 'Location 2080'
 'Location 1213' 'Location 1475' 'Location 1101' 'Location 1525'
 'Location 1129' 'Location 1660' 'Location 1850' 'Location 1898'
 'Location 1631' 'Location 1156' 'Location 1336' 'Location 1849'
 'Location 1965' 'Location 1975' 'Location 2004' 'Location 1073'
 'Location 1707' 'Location 2040' 'Location 1084' 'Location 1780'
 'Location 1079' 'Location 1160' 'Location 1399' 'Location 1397'
 'Location 2094' 'Location 1973' 'Location 1151' 'Location 1300'
 'Location 1721' 'Location 1319' 'Location 1679' 'Location 1581'
 'Location 1817' 'Location 1181' 'Location 1746' 'Location 1008'
 'Location 1689' 'Location 1841' 'Location 1820' 'Location 1499'
 'Location 2043' 'Location 1072' 'Location 1495' 'Location 1442'
 'Location 1357' 'Location 1921' 'Location 1355' 'Location 1567'
 'Location 1479' 'Location 1324' 'Location 1103' 'Location 1798'
 'Location 1789' 'Location 1697' 'Location 1068' 'Location 1696'
 'Location 1627' 'Location 1149' 'Location 1989' 'Location 1653'
 'Location 1664' 'Location 1083' 'Location 1376' 'Location 1106'
 'Location 1446' 'Location 2034' 'Location 1977' 'Location 1427'
 'Location 1030' 'Location 1428' 'Location 1961' 'Location 1693'
 'Location 1379' 'Location 1458' 'Location 1924' 'Location 1547'
 'Location 1605' 'Location 1170' 'Location 1964' 'Location 1742'
 'Location 1301' 'Location 1120' 'Location 1606' 'Location 1803'
 'Location 1049' 'Location 1417' 'Location 1434' 'Location 1071'
 'Location 1293' 'Location 2047' 'Location 1795' 'Location 1614'
 'Location 1710' 'Location 1267' 'Location 1875' 'Location 1691'
 'Location 1656' 'Location 1260' 'Location 1811' 'Location 1829'
 'Location 2057' 'Location 1665' 'Location 1102' 'Location 2019'
 'Location 1365' 'Location 1732' 'Location 1367' 'Location 1836'
 'Location 1122' 'Location 1337' 'Location 1784' 'Location 1032'
 'Location 2045' 'Location 1522' 'Location 1801' 'Location 1996'
 'Location 1162' 'Location 1201' 'Location 1988' 'Location 1743'
 'Location 1358' 'Location 1175' 'Location 1451' 'Location 1519'
 'Location 2058' 'Location 1570' 'Location 1163' 'Location 2079'
 'Location 1192' 'Location 1736' 'Location 1729' 'Location 1640'
 'Location 2072' 'Location 1244' 'Location 1263' 'Location 1343'
 'Location 1198' 'Location 1403' 'Location 1036' 'Location 1316'
 'Location 1413' 'Location 1719' 'Location 1551' 'Location 1254'
 'Location 1562' 'Location 1153' 'Location 1698' 'Location 1954'
 'Location 2088' 'Location 1976' 'Location 1923' 'Location 1804'
 'Location 1794' 'Location 1724' 'Location 1459' 'Location 1393'
 'Location 1993' 'Location 1753' 'Location 1222' 'Location 1216'
 'Location 1139' 'Location 1369' 'Location 1775' 'Location 1717'
 'Location 1568' 'Location 1318' 'Location 1546' 'Location 1922'
 'Location 1452' 'Location 1911' 'Location 1115' 'Location 1895'
 'Location 1856' 'Location 1908' 'Location 1616' 'Location 1760'
 'Location 1890' 'Location 1643' 'Location 1994' 'Location 1727'
 'Location 1992' 'Location 1557' 'Location 1956' 'Location 1462'
 'Location 2000' 'Location 2093' 'Location 1879' 'Location 1555'
 'Location 1464' 'Location 1099' 'Location 1950' 'Location 1386'
 'Location 2017' 'Location 1564' 'Location 1893' 'Location 1414'
 'Location 1377' 'Location 1078' 'Location 1749' 'Location 1398'
 'Location 1193' 'Location 1734' 'Location 1704' 'Location 1684'
 'Location 1373' 'Location 1768' 'Location 1215' 'Location 1116'
 'Location 1978' 'Location 1725' 'Location 1164' 'Location 2066'
 'Location 2059' 'Location 1871' 'Location 1277' 'Location 1313'
 'Location 1325' 'Location 1572' 'Location 1203' 'Location 1270'
 'Location 1604' 'Location 1119' 'Location 1410' 'Location 1930'
 'Location 1183' 'Location 1291' 'Location 1463' 'Location 1456'
 'Location 1625' 'Location 1563' 'Location 1023' 'Location 1611'
 'Location 1169' 'Location 1937' 'Location 1681' 'Location 1540'
 'Location 1687' 'Location 1143' 'Location 1613' 'Location 1266'
 'Location 1560' 'Location 1380' 'Location 1806' 'Location 1019'
 'Location 1269' 'Location 1014' 'Location 1508' 'Location 1688'
 'Location 2009' 'Location 1202' 'Location 1388' 'Location 1731'
 'Location 1204' 'Location 1902' 'Location 1826' 'Location 1211'
 'Location 1477' 'Location 1802' 'Location 1602' 'Location 1396'
 'Location 1837' 'Location 1536' 'Location 1880' 'Location 1860'
 'Location 1173' 'Location 1490' 'Location 1043' 'Location 1237'
 'Location 1769' 'Location 2055' 'Location 1389' 'Location 1455'
 'Location 1888' 'Location 1383' 'Location 1960' 'Location 1165'
 'Location 1758' 'Location 1909' 'Location 1903' 'Location 1280'
 'Location 1740' 'Location 1914' 'Location 2028' 'Location 1628'
 'Location 1674' 'Location 1701' 'Location 1790' 'Location 1936'
 'Location 1854' 'Location 1779' 'Location 1484' 'Location 2020'
 'Location 1061' 'Location 1390' 'Location 1059' 'Location 1333'
 'Location 1647' 'Location 2035' 'Location 1065' 'Location 1868'
 'Location 2086' 'Location 1340' 'Location 1022' 'Location 1825'
 'Location 1905' 'Location 1763' 'Location 1716' 'Location 2015']

PropertyDamage has 3 unique values: ['?' 'YES' 'NO']
Witnesses has 5 unique values: ['0' '1' '3' '2' 'MISSINGVALUE']
PoliceReport has 3 unique values: ['?' 'YES' 'NO']
AmountOfTotalClaim has 21976 unique values: ['65501' '61382' '66755' ... '7262' '74547' '55830']

## Notes:
 - Replace values with N/A or Null:
     - PropertyDamage: ?
     - Witnesses: MISSINGVALUE
     - PoliceReport: ?
     - TypeOfCollision: ?
     -

# Exploring Train_Policy.csv

In [55]:
df_policy = pd.read_csv('Datasets/Train_Policy.csv')
df_policy.head(2)

,InsurancePolicyNumber,CustomerLoyaltyPeriod,DateOfPolicyCoverage,InsurancePolicyState,Policy_CombinedSingleLimit,Policy_Deductible,PolicyAnnualPremium,UmbrellaLimit,InsuredRelationship,CustomerID
0,110122,328,2014-10-17,State3,250/500,1000,1406.91,0,husband,Cust1001
1,110125,256,1990-05-25,State1,250/500,2000,1415.74,6000000,unmarried,Cust1004

In [57]:
describe_df(df_policy)

DataFrame Shape: (28836, 10)
       InsurancePolicyNumber  CustomerLoyaltyPeriod  Policy_Deductible  \
count           28836.000000           28836.000000       28836.000000
mean           129312.517097             203.067867        1114.282529
std             11114.060267              99.932951         546.632816
min            110122.000000               1.000000         500.000000
25%            119698.750000             126.000000         622.000000
50%            129278.500000             199.000000        1000.000000
75%            138933.250000             267.000000        1627.000000
max            148619.000000             479.000000        2000.000000

       PolicyAnnualPremium  UmbrellaLimit
count         28836.000000   2.883600e+04
mean           1255.528382   9.836680e+05
std             223.013899   1.969282e+06
min              -1.000000  -1.000000e+06
25%            1122.007500   0.000000e+00
50%            1265.205000   0.000000e+00
75%            1396.605000   4.859610e+05
max            2047.590000   1.000000e+07
InsurancePolicyNumber         0
CustomerLoyaltyPeriod         0
DateOfPolicyCoverage          0
InsurancePolicyState          0
Policy_CombinedSingleLimit    0
Policy_Deductible             0
PolicyAnnualPremium           0
UmbrellaLimit                 0
InsuredRelationship           0
CustomerID                    0
dtype: int64
DateOfPolicyCoverage has 6779 unique values: ['2014-10-17' '1990-05-25' '2014-06-06' ... '2007-04-18' '2014-01-07'
 '2010-12-14']
InsurancePolicyState has 3 unique values: ['State3' 'State1' 'State2']
Policy_CombinedSingleLimit has 9 unique values: ['250/500' '500/1000' '100/300' '250/300' '100/500' '250/1000' '100/1000'
 '500/500' '500/300']
InsuredRelationship has 6 unique values: ['husband' 'unmarried' 'own-child' 'wife' 'other-relative' 'not-in-family']
CustomerID has 28836 unique values: ['Cust1001' 'Cust1004' 'Cust1005' ... 'Cust39495' 'Cust39497' 'Cust39498']

# Train_Vehicle.csv

In [58]:
df_vehicle = pd.read_csv('Datasets/Train_Vehicle.csv')
df_vehicle.head(2)

  CustomerID VehicleAttribute VehicleAttributeDetails
0  Cust20179        VehicleID             Vehicle8898
1  Cust21384     VehicleModel                  Malibu

In [62]:
describe_df(df_vehicle)

DataFrame Shape: (115344, 3)
       CustomerID VehicleAttribute VehicleAttributeDetails
count      115344           115344                  115344
unique      28836                4                   28911
top     Cust20179        VehicleID                    Saab
freq            4            28836                    2415
CustomerID                 0
VehicleAttribute           0
VehicleAttributeDetails    0
dtype: int64

In [60]:
df_vehicle['VehicleAttribute'].unique()

array(['VehicleID', 'VehicleModel', 'VehicleMake', 'VehicleYOM'],
      dtype=object)

In [61]:
df_vehicle['VehicleAttributeDetails'].unique()

array(['Vehicle8898', 'Malibu', 'Toyota', ..., 'Vehicle28831',
       'Vehicle12870', 'Vehicle19680'], dtype=object)

## Notes:
 - Need to pivot data to re-establish attributes here

# Traindata_with_Target.csv

In [64]:
df_with_target = pd.read_csv('Datasets\Traindata_with_Target.csv')
df_with_target.head(2)

  CustomerID ReportedFraud
0  Cust20065             N
1  Cust37589             N

In [69]:
df_with_target.shape

(28836, 2)

In [68]:
df_with_target['ReportedFraud'].unique()

array(['N', 'Y'], dtype=object)

# Traindata_withoutTarget.xlsx

In [65]:
df_without_target = pd.read_excel('Datasets\Traindata_withoutTarget.xlsx')
df_without_target.head(2)

  CustomerID  ReportedFraud
0  Cust20065            NaN
1  Cust37589            NaN

In [70]:
df_without_target.shape

(28836, 2)

In [66]:
df_without_target['ReportedFraud'].unique()

array([nan])