# Exercise 5.2: Gibbs Sampling

This example again uses the student model but only the variables intll and SAT.
The sampling process generates the next state by sampling one variable given the Markov blanket.
The output shows which state the model is in for each sample.

In [4]:
#This code is modified from the examples at pgmpy.org Copyright (c) 2013-2021 pgmpy
from pgmpy.factors.discrete import TabularCPD
from pgmpy.models import BayesianModel
intel_cpd = TabularCPD('intel', 2, [[0.7], [0.3]])
sat_cpd = TabularCPD('sat', 2, [[0.95, 0.2], [0.05, 0.8]], evidence=['intel'], evidence_card=[2])
student = BayesianModel()
student.add_nodes_from(['intel', 'sat'])
student.add_edge('intel', 'sat')
student.add_cpds(intel_cpd, sat_cpd)
from pgmpy.sampling import GibbsSampling
gibbs_chain = GibbsSampling(student)
sampled = gibbs_chain.sample(size=10)
sampled

C:\Users\wesle\AppData\Roaming\Python\Python39\site-packages\pgmpy\models\BayesianModel.py:8: FutureWarning: BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
  warnings.warn(

  0%|          | 0/9 [00:00<?, ?it/s]

   intel  sat
0      0    1
1      1    1
2      0    0
3      0    0
4      0    0
5      0    0
6      0    0
7      0    0
8      0    0
9      0    0

As in the previous exercise we can sum up the number of times the model is in a particular state and normailse these to estimate the required probability.

In [5]:
#To select a row based on multiple conditions you can use &:
SATandIntel = sampled.loc[(sampled['intel'] == 1) & (sampled['sat']==1)]
SATandIntel

   intel  sat
1      1    1

In [6]:
#find number of rows in dataframe
SATandIntel.shape[0]

1

Change the number of samples taken and calculate the estiamtes for the CPDs from the results to verify the method converges.